### ISSUE TITLE
Crash When Using New Dynamic Lights Version

### ISSUE THREAD

**Issue by Darkosto** [illusivesoulworks/radiantgear#1]
Heya C4!

I just got around to updating to 1.18.2 and dynamic has updated to solve some worldgen issues. I dropped in the latest CuriousLights version and I'm getting a crash on world load. I suspect it has something to do with the latest dynamic lights update?

Thanks!

MC: 1.18.2
Forge: 40.0.49
Dynamic Lights: 1.18.6
CuriousLights: 1.0.0+ 1.18.2

Crash report: https://pastebin.com/uSPdNgC1 https://pastebin.com/Dc7S4bh9

**Comment by TheIllusiveC4** [comment]
Yeah, probably just need to update the mod to the latest Dynamic Lights.

**Comment by Darkosto** [comment]
Thank you!
