### ISSUE TITLE
Lighting issue with Curios slot (CuriousLanterns)

### ISSUE THREAD

**Issue by Typhonidite** [illusivesoulworks/radiantgear#12]
Using CuriousLanterns, a lantern is put into the Curios Hip slot. When on the hip, the dynamic lighting provided seems to be delayed within other chunks.

![2023-01-31_20 55 46](https://user-images.githubusercontent.com/71224403/215934188-1efe1efd-c383-467c-b991-cb2f8eb13c86.png)
![2023-01-31_20 56 01](https://user-images.githubusercontent.com/71224403/215934260-d12118ab-9c03-498a-8ad1-73938215192d.png)
It's important to note that the lighting is only _delayed_. It just seems to load at a far slower refresh rate.

I didn't know if this would be a RadiantGear issue or a CuriousLanterns issue, but seeming that it has to do with the lighting itself, I thought it would be best to report the issue here.
I _am_ using Optifine, but Dynamic Lighting is off.

**Comment by TheIllusiveC4** [comment]
A few things to verify first:
1. Which dynamic lighting mod are you using?
2. Have you compared using the lantern normally and equipped? Is it the same, or different?
3. Does this still happen if you remove Optifine entirely?
