### ISSUE TITLE
Can you make it work with shaders like BSL using oculus?

### ISSUE THREAD

**Issue by Panderine** [illusivesoulworks/radiantgear#13]
Hello ! Magnesium Dynamic Lights seems "choppy" even using realtime lightning if you look at the floor while moving you see the lighting efect. While using oculus with a dynamic light capable shader like BSL or complementary the effect is completly different, no "choppiness". Dunno if its possible to make the lantern at the hip work like an emissive block under those shaders. Thanks !!

**Comment by TheIllusiveC4** [comment]
Does Oculus and the shaders make the lantern emit dynamic lighting when held normally?

**Comment by Panderine** [comment]
yes

**Comment by TheIllusiveC4** [comment]
Hmm, so I _think_ this would require integration from the shader or Oculus. I'm not completely sure though, but I think adding something like this on my end would require knowledge about how to code shaders and that's way beyond my current skillset. Either way, it's not something I think I could reasonably accomplish unfortunately.

**Comment by Panderine** [comment]
Thanks anyway for having a look at it!
