### ISSUE TITLE
[Feature]: Add existing items to this mod's bridge via config

### ISSUE THREAD

**Issue by genderneutralnoun** [illusivesoulworks/radiantgear#15]
### What is the new feature or improvement?

Add the ability to define in a config file pre-existing items (such as the vanilla lantern, or a mod-added lantern) that create a glow via the user's installed dynamic lights mod when equipped via Curios/Trinkets. Preferably also with the ability to define a Curios/Trinkets slot for the item as well. This would allow users for whom creating their own mod is not possible to support their own vanilla or mod-added light sources without having to depend on a modder implementing it for them. Teach a man to fish and all that.
I don't know how you would implement this, but it would be a HUGE help to all of us. And since Forge already has Curious Lanterns, I suggest prioritizing the Fabric and Trinkets implementation, if you decide to implement this feature. Thank you in advance.
It wouldn't supersede Curious Lanterns I don't think because Curious Lanterns is drag-and-drop, and it enables visible lanterns on the player, which I wouldn't expect you to support unless you really wanted to.

**Comment by TheIllusiveC4** [comment]
As far as I'm aware, what you're asking for can be done already without mods. The two-step process for adding an existing item as a source of dynamic lighting in an accessory slot is:

1. Add that item to the dynamic light mod's configuration file, if it's not already there. Every dynamic lighting mod should have something like this, as far as I'm aware, where users can specify items and their respective light level.
2. Add that item to the appropriate Curios/Trinkets item tag via a datapack.

After that, the item will provide dynamic lighting in the slot it's equipped in automatically. Both of these steps can be done without any modding implementation or coding involved.

**Comment by genderneutralnoun** [comment]
I see. I couldn't find any documentation I could understand on how to make a datapack like that for Curios or Trinkets. I've fallen off on minecraft modding (as you can probably guess from my late reply) but if (more like when lol) I return I'll probably give it a shot again. In the meantime if you know of any resources that might help someone who's completely new to datapack authoring, I'd appreciate it if you shared them. For some reason, finding minecraft modding resources via Google is really hard...

**Comment by TheIllusiveC4** [comment]
This gives an overview about datapacks:
https://minecraft.wiki/w/Data_pack

And towards the bottom of this page is a short guided walkthrough on creating the item tag within the datapack for Curios:
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users

The same principle applies for Trinkets:
https://github.com/emilyploszaj/trinkets/wiki/Quick-Start-Guide
