### ISSUE TITLE
[Bug]: Doesn't seem to work with Ryonamic Lights

### ISSUE THREAD

**Issue by brisingraerowing** [illusivesoulworks/radiantgear#16]
### Minecraft Version

1.19.2

### What happened?

No dynamic lights with a lantern and Curios Lanterns, [Ryonamic Lights](https://www.curseforge.com/minecraft/mc-mods/ryoamiclights) and this mod.

### How do you trigger this bug?

1. Use above listed mods
2. Observe no lights with lantern on belt slot

### Loader

Forge

### Loader Version

43.3.2

### Mod Version

2.0.1

**Comment by Sshmoob** [comment]
I am also able to reproduce this issue. 
Note that Ryonamic lights is working fine, as the lantern does light up the surrounding area when held in your hand rather than in the belt slot.

**Comment by DTech10** [comment]
same
