### ISSUE TITLE
[Feature]: Armor support

### ISSUE THREAD

**Issue by mxnmnm** [illusivesoulworks/radiantgear#19]
### What is the new feature or improvement?

I want armor to be supported as well as baubles for a more consistent experience. It's kinda weird having a bauble that lights up when in the bauble slot but not your armor slot.

**Comment by TheIllusiveC4** [comment]
As far as I'm aware, most, if not all, of the dynamic light mods have native support for items placed in armor slots. I've just tested Lucent, Dynamic Lights, and multiple permutations of LambDynamicLights for verification and they all provide dynamic lighting from the armor slots.

**Comment by mxnmnm** [comment]
What about ars noveau?

**Comment by TheIllusiveC4** [comment]
It seems like Ars Nouveau doesn't, based on my testing. Since it seems most of the other dynamic lights have native support for armor, you should probably ask the Ars Nouveau developer about adding this sort of feature.
