### ISSUE TITLE
[Bug]: Lanterns will not go into a Relics belt slot

### ISSUE THREAD

**Issue by ghost** [illusivesoulworks/radiantgear#20]
### Minecraft Version

1.19.2

### What happened?

Lanterns simply refuse to be put into a belt slot in 1.19.2.
I've used Radiant Gear before in 1.20.1 and it works just fine when using this slot. I'm using the Curios API mod (Version 5.1.6.1) and the dynamic light mod Embeddium/Rubidium Dynamic Lights [Aka Magnesium/Rubidium Dynamic lights] (Version 1.4.0) and Embeddium/Rubidium Extras (Version 1.4.3) Since Curios doesn't have preset slots, the mod Relics (Version 0.4.7.5) is required to boot up the belt slot.

### How do you trigger this bug?

1. Open Minecraft 1.19.2 with the above mods installed.
2. Attempt to place a lantern into the belt slot.

### Loader

Forge

### Loader Version

43.3.7

### API Version

N/A

### Mod Version

2.0.2+1.19.2

**Comment by TheIllusiveC4** [comment]
Radiant Gear only provides dynamic lighting support, it does not add any additional contents or features such as being able to place lanterns into accessory slots.
