### ISSUE TITLE
[Bug]: radiantgear-forge-2.0.3+1.19.2.jar being detected by Windows Defender as a Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by TheEvilFusion** [illusivesoulworks/radiantgear#23]
### Minecraft Version

1.19.2

### What happened?

I downloaded the latest 1.19.2 forge version from Curseforge and after putting it into my mod pack via Prismlauncher, Windows Defender detected it as a severe threat, calling it a Trojan:Script/Wacatac.B!ml. i believe this is a false positive but it gave me quiet the panic. Sorry if this isn’t how these go usually, just made an account on Github to report this.

### How do you trigger this bug?

1. Downloaded the most recent 1.19.2 version of Radiant gear for forge.
2. Click on the “Add files” button on Prismlauncher and added the mod to my mod list.
3. Before i even started the game, Windows Defender popped up saying there were infected files on my computer
...

### Loader

Forge

### Loader Version

Forge 43.3.0

### Mod Version

radiantgear-forge-2.0.3+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
I've scanned the file downloaded directly from CurseForge on both my personal computer with Windows Defender and VirusTotal:
https://www.virustotal.com/gui/file/5d9b92540f673e71319beb65f3c89af50ef98bb75777081a00e745ebdada048f/detection

Nothing shows up or is flagged as malicious. It could be a false positive in your case, but just to be sure, I'd recommend redownloading it from CurseForge (especially if you downloaded it from somewhere else previously) and also scanning your system itself for other files that could be infected instead.
