### ISSUE TITLE
[Feature]: add slots for vanilla lights

### ISSUE THREAD

**Issue by R0gyman** [illusivesoulworks/radiantgear#24]
I don't know why you expect everyone to manually add slots it would be really nice if you added this by default

**Comment by TheIllusiveC4** [comment]
It's not that I expect everyone to manually add slots, it's that this isn't a content mod. It's a compatibility mod that makes dynamic lights work in Curios/Trinkets slots. The expectation is that other mods, which are already using Curios or Trinkets slots, are adding slots you can use.

To understand why the distinction is important, it's that adding any slots to this mod means that everyone who wants dynamic lights in accessory slots has to abide by what is added. And not everyone is going to agree on what kind of slots they want.

If I add a belt slot, everyone who wants the dynamic lights feature must commit to getting that belt slot even if they actually just want like a head slot for a mining helmet or something. It's the difference between "I have to download Radiant Gear and (whichever other mod that already has the items/slots the way I want)" and "I have to download Radiant Gear, which comes with its own slot(s), which aren't exactly what I want so now I have to configure it to my specification."

Ideally, what you're actually asking for are mods like [Curious Lanterns](https://www.curseforge.com/minecraft/mc-mods/curious-lanterns) that use Radiant Gear as a bridge to add the content you're looking for in a specific kind of way (in that specific case, lanterns in a belt slot).
