### ISSUE TITLE
[Bug]: Crashes with Embeddium++ 1.2.10

### ISSUE THREAD

**Issue by kakashi1464** [illusivesoulworks/radiantgear#27]
### Minecraft Version

1.20.1

### What happened?

I expected everything to work fine with embeddium++.

### How do you trigger this bug?

1.Install embeddium++ and radiant gear with their dependecies 
2.Run Minecraft
3.Enter world

### Loader

Forge

### Loader Version

Neoforge 47.1.104

### Mod Version

Radiant Gear 2.1.4+1.20.1

### Relevant Log Outputs

[latest.log](https://gist.github.com/kakashi1464/8abd545814d80c3a01fd1feded9f5bf6)
[debug.log](https://gist.github.com/kakashi1464/d8e28ded37b54676ec8e7ea5910948fd)
[crash-report](https://gist.github.com/kakashi1464/a559e49037e6d866f9eb038b0831c89c)

**Comment by katubug** [comment]
Came here to report this as well. I am using Forge.

**Comment by tr1kright** [comment]
The same thing happens on 1.19.2
