### ISSUE TITLE
[Bug]: Light not emiting from belt slot with Sodium/Embeddium Dynamic Lights

### ISSUE THREAD

**Issue by raffle2** [illusivesoulworks/radiantgear#33]
### Minecraft Version

1.20.1

### What happened?

In recent versions of [Sodium/Embeddium Dynamic Lights](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged), the lantern no longer emits light when equipped in the player's belt slot. This feature worked prior to version 1.60 but stopped functioning afterward. According to the mod author, this is due to changes in their API, as noted [here](https://github.com/txnimc/SodiumDynamicLights/issues/13#issuecomment-2366867680).

Thank you for reading!

### How do you trigger this bug?

1. Install Radiant Gear
2. Install Sodium/Embeddium Dynamic Lights
3. Put lantern in belt slot
4. No light is casted from the player
...

### Loader

Forge

### Loader Version

47.3.0

### Mod Version

radiantgear-forge-2.1.5+1.20.1

**Comment by FullMetalMaster** [comment]
radiantgear needs to be updated to match the new api

**Comment by FullMetalMaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/ryoamiclights/comments

RyoamicLights fixes the issue with the hip light

**Comment by LawOfSynergy** [comment]
1.20.1 version of radiant gear was missing the integration with sodium dynamic lights

This pull request adds that: https://github.com/illusivesoulworks/radiantgear/pull/36
